name: CI macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  local-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ macos-11, macos-12 ]
    steps:
      - uses: actions/checkout@v3
      - name: Brew install
        run: brew install --build-from-source --force ./sage.rb
      - name: Compile code
        run: sage setup.py develop
      - name: Foo
        run: ls /usr/local/bin/