name: CI macOS

## This GitHub Actions workflow runs SAGE_ROOT/tox.ini with select environments,
## whenever a GitHub pull request is opened or synchronized in a repository
## where GitHub Actions are enabled.
##
## It builds and checks some sage spkgs as defined in TARGETS.
##
## A job succeeds if there is no error.
##
## The build is run with "make V=0", so the build logs of individual packages are suppressed.
##
## At the end, all package build logs that contain an error are printed out.
##
## After all jobs have finished (or are canceled) and a short delay,
## tar files of all logs are made available as "build artifacts".

#on: [push, pull_request]

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
  workflow_dispatch:
    # Allow to run manually

jobs:
  local-macos-nohomebrew:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        # os: [ macos-11, macos-12 ]
        os: [ macos-12 ]
    steps:
      - uses: actions/checkout@v3
      - name: Brew install
        run: brew install --build-from-source ./sage.rb
      - name: Compile code
        run: sage setup.py develop
      - name: Test with python
        run: python3 setup.py develop
      - name: Foo
        run: ls /Applications/SageMath-9-5.app/Contents/MacOS/
      - name: Foo
        run: /Applications/SageMath-9-5.app/Contents/MacOS/SageMath setup.py develop